import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata: Metadata = {
  title: "DevTrekker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <meta content="width=device-width, initial-scale=0" name="viewport" />
       <body className="min-h-screen bg-black-100 font-poppins">
       <SpeedInsights/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
